version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --docker --docker.domain=yourdomain.com
    ports:
      - 88:80
      - 8008:443
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./traefik.yaml:/traefik.yaml
      - ./route.yaml:/route.yaml
      - ./acme.json:/acme.json
    restart: always