version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "88:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8008:8080"
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./traefik.yaml:/traefik.yaml
      - ./route.yaml:/route.yaml
      - ./acme.json:/acme.json
    restart: always