version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "88:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8008:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  whoami:
  # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.api-back-router.rule=Host(`api-dev.151-plus.com`)"
      - "traefik.http.routers.api-back-router.service=151-plus-api-service"
      - "traefik.http.services.151-plus-api-service.loadbalancer.servers[0].url=http://172.18.0.2:8080"
      - "traefik.http.services.151-plus-api-service.loadbalancer.servers[1].url=http://172.18.0.2:8081"